### ISSUE TITLE
Database Driver

### ISSUE THREAD

**Issue by belankus** [arifhp86/laravel-clear-expired-cache-file#8]
Great package Pak, if i'm not mistaken there is folder deletion option. Does this package run smoothly also with database driver cache? And does it now support for Laravel 11. Thanks in Adnvance!

**Comment by Vectorial1024** [comment]
Looking at the source code (it is quite small and simple) this package currently only clears the file cache.

The main challenge for clearing the database cache is that for the default Laravel database cache table ("cache"), there is no index on the "expiration" column. So:

- `DELETE FROM cache WHERE expiration <= UNIX_TIMESTAMP(NOW())` will do a full table scan and will likely lock the entire table for a long time
- Doing "chunk all keys, check expiration" will be slow

Also, perhaps the cache clearing should also check the "cache_locks" table for potential key locks.

We'll see how the team thinks about this.

**Comment by belankus** [comment]
thanks for your response. it will be great to be happen. since atleast for now, serverless application has a massive growth, and file caching now become preference.

We're looking for more option as alternatives of redis and dynamoDB. for my bare ideas, maybe by modify default migrations of `cache` table is one of the feature

**Comment by Vectorial1024** [comment]
@belankus 

Eventually, I have created a new package that removes not only `file` expired data, but also `database` expired data.

- GitHub https://github.com/Vectorial1024/laravel-cache-evict/
- Packagist https://packagist.org/packages/vectorial1024/laravel-cache-evict

This should be helpful in the case of serverless apps that uses file/database storage. The default Laravel database cache migration is not modified, so that the package can work with most amount of Laravel apps.
